### ISSUE TITLE
Standardise db.Model fields

### ISSUE THREAD

**Issue by brandontjd** [wonderful-group-smu/spm-G9#6]
# Summary

Based on the rough sketch of the ER diagram, we have named our fields a certain way. E.g. `user_id` , instead of `id`. At the moment, some models aren't synced up and I don't want to change them on my own branch (SPM-33). Therefore I'm proposing the following:

1. We create a new commit on branch release1 to fix the names on the existing table
2. All downstream branches to merge release1 into theirs to resolve the issue 

Should this be approved, I'll go ahead and do it then we can OTOT merge the branch into our respective working branches.

**Comment by brandontjd** [comment]
Approved

**Comment by yarkhinephyo** [comment]
I agree. It may be better to keep the "id" first because the refactoring will increase development time and we are a bit behind in our sprint #1.
